'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Building2, ClipboardCheck, CreditCard, MessageSquareText, PoundSterling, Users } from 'lucide-react'
import { Card } from '@/components/dashboard/ui'
import { apiClient, ApiClientError } from '@/lib/api/client'

type Dashboard = { totals: { users: number; practices: number; pendingPractices: number; pendingReviews: number; activeSubscriptions: number; revenue: string }; recentPractices: Array<{ id: string; name: string; status: string; createdAt: string }> }

export function AdminDashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState('')
  useEffect(() => { void apiClient<Dashboard>('/api/admin/dashboard').then(setData).catch((caught) => setError(caught instanceof ApiClientError ? caught.message : 'Dashboard could not be loaded.')) }, [])
  const stats = data ? [{ label: 'Users', value: data.totals.users, icon: Users }, { label: 'Practices', value: data.totals.practices, icon: Building2 }, { label: 'Pending practices', value: data.totals.pendingPractices, icon: ClipboardCheck }, { label: 'Pending reviews', value: data.totals.pendingReviews, icon: MessageSquareText }, { label: 'Active subscriptions', value: data.totals.activeSubscriptions, icon: CreditCard }, { label: 'Revenue', value: new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(Number(data.totals.revenue)), icon: PoundSterling }] : []
  return <div className="min-w-0 space-y-6"><section className="flex flex-col gap-4 rounded-2xl bg-white p-4 shadow-lg shadow-black/10 sm:p-5 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><h1 className="dashboard-heading text-[34px] font-normal text-black sm:text-5xl">Admin dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Live directory, moderation and revenue totals.</p></div><Link href="/admin-dashboard/pending-approvals" className="inline-flex w-full justify-center rounded-lg bg-[#064071] px-4 py-3 text-sm font-semibold text-white md:w-auto">Review approvals</Link></section>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{!data ? <Card className="p-10 text-center text-sm text-muted-foreground">Loading dashboard...</Card> : <><section className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map((stat) => { const Icon = stat.icon; return <Card key={stat.label} className="p-4 sm:p-5"><div className="flex min-w-0 items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm text-muted-foreground">{stat.label}</p><p className="mt-2 break-words text-2xl font-semibold text-black">{stat.value}</p></div><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#EEF7F5] text-[#01AEAD]"><Icon className="size-5" /></span></div></Card> })}</section><Card className="overflow-hidden p-0"><div className="flex items-center justify-between gap-3 border-b p-4 sm:p-5"><h2 className="font-semibold">Recent practices</h2><Link href="/admin-dashboard/veterinary-practice" className="shrink-0 text-sm font-semibold text-[#01AEAD]">View all</Link></div>{data.recentPractices.map((practice) => <div key={practice.id} className="flex flex-col gap-2 border-b px-4 py-4 last:border-0 sm:flex-row sm:items-center sm:justify-between sm:gap-4 sm:px-5"><div className="min-w-0"><p className="break-words font-semibold text-black">{practice.name}</p><p className="text-xs text-muted-foreground">Added {new Date(practice.createdAt).toLocaleDateString('en-GB')}</p></div><span className="w-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{practice.status}</span></div>)}</Card></>}</div>
}
