'use client'

import { useEffect, useState } from 'react'
import { Card } from '@/components/dashboard/ui'
import { apiClient, ApiClientError } from '@/lib/api/client'
import { AdminPageBanner } from '../shared/admin-page-banner'

type Profile = { firstName: string; lastName: string; email: string; phone: string | null }
type Settings = { backupEmail: string | null; locale: string; emailNotifications: boolean; moderationNotifications: boolean; billingNotifications: boolean }

export function AdminSettingsPage() {
  const [profile, setProfile] = useState<Profile>({ firstName: '', lastName: '', email: '', phone: null }); const [settings, setSettings] = useState<Settings>({ backupEmail: null, locale: 'en-GB', emailNotifications: true, moderationNotifications: true, billingNotifications: true }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirm: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([apiClient<Profile>('/api/users/me/profile'), apiClient<Settings | null>('/api/admin/settings')]).then(([user, saved]) => { setProfile(user); if (saved) setSettings(saved) }).catch((caught) => setError(caught instanceof ApiClientError ? caught.message : 'Settings could not be loaded.')) }, [])
  async function save() { setError(''); try { await Promise.all([apiClient('/api/users/me/profile', { method: 'PUT', body: JSON.stringify({ firstName: profile.firstName, lastName: profile.lastName, phone: profile.phone }) }), apiClient('/api/admin/settings', { method: 'PUT', body: JSON.stringify(settings) })]); setMessage('Settings saved.') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Settings could not be saved.') } }
  async function updatePassword() { if (password.newPassword !== password.confirm) { setError('New passwords do not match.'); return } try { await apiClient('/api/users/me/password', { method: 'PUT', body: JSON.stringify({ currentPassword: password.currentPassword, newPassword: password.newPassword }) }); setPassword({ currentPassword: '', newPassword: '', confirm: '' }); setMessage('Password updated. Please sign in again on other devices.') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Password could not be updated.') } }
  return <div className="space-y-6"><AdminPageBanner title="Account Settings" description="Persisted admin profile and notification preferences." />{message && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="grid gap-6 lg:grid-cols-2"><Card className="grid gap-4 p-6"><h2 className="font-semibold">Profile</h2><Input label="First name" value={profile.firstName} onChange={(value) => setProfile({ ...profile, firstName: value })} /><Input label="Last name" value={profile.lastName} onChange={(value) => setProfile({ ...profile, lastName: value })} /><Input label="Email" value={profile.email} readOnly /><Input label="Phone" value={profile.phone ?? ''} onChange={(value) => setProfile({ ...profile, phone: value || null })} /><Input label="Backup email" value={settings.backupEmail ?? ''} onChange={(value) => setSettings({ ...settings, backupEmail: value || null })} /><Input label="Locale" value={settings.locale} onChange={(value) => setSettings({ ...settings, locale: value })} /><button onClick={() => void save()} className="h-10 rounded-md bg-[#01AEAD] text-sm font-semibold text-white">Save settings</button></Card><Card className="grid gap-4 p-6"><h2 className="font-semibold">Notifications</h2>{(['emailNotifications','moderationNotifications','billingNotifications'] as const).map((key) => <label key={key} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{key.replace(/([A-Z])/g, ' $1')}</span><input type="checkbox" checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })} /></label>)}<h2 className="mt-3 font-semibold">Change password</h2><Input label="Current password" type="password" value={password.currentPassword} onChange={(value) => setPassword({ ...password, currentPassword: value })} /><Input label="New password" type="password" value={password.newPassword} onChange={(value) => setPassword({ ...password, newPassword: value })} /><Input label="Confirm password" type="password" value={password.confirm} onChange={(value) => setPassword({ ...password, confirm: value })} /><button onClick={() => void updatePassword()} className="h-10 rounded-md border text-sm font-semibold">Update password</button></Card></div></div>
}
function Input({ label, value, onChange, readOnly, type = 'text' }: { label: string; value: string; onChange?: (value: string) => void; readOnly?: boolean; type?: string }) { return <label className="text-sm font-medium">{label}<input type={type} value={value} readOnly={readOnly} onChange={(event) => onChange?.(event.target.value)} className="mt-2 h-10 w-full rounded-md border px-3 text-sm read-only:bg-slate-50" /></label> }
